//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BodyScanner.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BodyScanner.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body Scanner.
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error initializing application:
        ///{0}.
        /// </summary>
        internal static string InitializationError {
            get {
                return ResourceManager.GetString("InitializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error initializing scanning:
        ///{0}.
        /// </summary>
        internal static string InitScanError {
            get {
                return ResourceManager.GetString("InitScanError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplied mesh contains invalid data.
        /// </summary>
        internal static string InvalidMeshArgument {
            get {
                return ResourceManager.GetString("InvalidMeshArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinect sensor is not available..
        /// </summary>
        internal static string KinectNotAvailable {
            get {
                return ResourceManager.GetString("KinectNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your name before scanning.
        /// </summary>
        internal static string PromptEnterName {
            get {
                return ResourceManager.GetString("PromptEnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning aborted.
        /// </summary>
        internal static string PromptScanAborted {
            get {
                return ResourceManager.GetString("PromptScanAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning completed.
        /// </summary>
        internal static string PromptScanCompleted {
            get {
                return ResourceManager.GetString("PromptScanCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning in process... Please turn around slowly.
        /// </summary>
        internal static string PromptScanning {
            get {
                return ResourceManager.GetString("PromptScanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stand in front of the sensor at about 2.5m distance to begin scanning.
        /// </summary>
        internal static string PromptToBeginScan {
            get {
                return ResourceManager.GetString("PromptToBeginScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanned frames: {0}
        ///Alignment energy: {1}.
        /// </summary>
        internal static string ScanningStatus {
            get {
                return ResourceManager.GetString("ScanningStatus", resourceCulture);
            }
        }
    }
}
